name: My First Github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      - name: Install node_modules
        run: npm
      - name: Build the project
        run: npm build
      - name: setup finish
        run: echo "hurray!"